from __future__ import annotations
import json, html
from pathlib import Path
CLAIM="SecureRails is AI-agent security governance and proof-bound defensive remediation. It is not autonomous cybersecurity certification, not offensive cyber, not a high-risk decision system by intended purpose, not a GPAI model provider by default, and not an investment product."

def _j(path: Path): return json.loads(path.read_text(encoding='utf-8')) if path.exists() else []

def build_data(registry: Path, out: Path) -> None:
    out.mkdir(parents=True, exist_ok=True)
    w,m,s,st=[_j(registry/f) for f in ('work_vaults.json','mark_allocations.json','sovereigns.json','settlements.json')]
    for n,v in [('work_vaults.json',w),('mark_allocations.json',m),('sovereigns.json',s),('settlements.json',st)]:
        (out/n).write_text(json.dumps(v,indent=2,sort_keys=True)+"\n")
    counters=['raw_secret_leak_count','external_target_scan_count','exploit_execution_count','malware_generation_count','social_engineering_content_count','unsafe_automerge_count','critical_safety_incidents']
    summary={"generated_at":"1970-01-01T00:00:00Z","work_vault_count":len(w),"open_vault_count":sum(1 for x in w if x.get('status') in ('vault_opened','example_not_production')),"accepted_vault_count":sum(1 for x in w if x.get('status')=='accepted'),"rejected_vault_count":sum(1 for x in w if x.get('status')=='rejected'),"pending_human_review_count":sum(1 for x in w if x.get('evidence',{}).get('human_review_status') in ('pending','not_reported')),"all_hard_safety_counters_zero":all(all((x.get('hard_safety_counters',{}).get(k,0)==0) for k in counters) for x in w),"sovereign_count":len(s),"mark_allocation_count":len(m),"settlement_record_count":len(st),"claim_boundary":CLAIM}
    (out/'summary.json').write_text(json.dumps(summary,indent=2,sort_keys=True)+"\n")

def render_html(registry: Path, out: Path) -> None:
    d = out / '_data'; build_data(registry, d)
    w,m,s=[_j(d/f) for f in ('work_vaults.json','mark_allocations.json','sovereigns.json')]
    sm=_j(d/'summary.json')
    chain='AI-agent work event → Work Vault → MARK → Sovereign → AGI Job → ProofBundle → Evidence Docket → validator decision → Human Review → $AGIALPHA Utility Settlement → Capability Archive → vNext Defensive Work'
    def td(x): return f'<td>{html.escape(str(x))}</td>'
    wrows=''.join('<tr>'+''.join([td(v.get('vault_id','unavailable')),td(v.get('status','unavailable')),td(v.get('mark_allocation',{}).get('assigned_sovereign','unavailable')),td(v.get('mark_allocation',{}).get('risk_tier','unavailable')),td(v.get('mark_allocation',{}).get('review_priority','unavailable')),td(v.get('evidence',{}).get('proofbundle_id','pending')),td(v.get('evidence',{}).get('evidence_docket_id','pending')),td(v.get('evidence',{}).get('human_review_status','pending')),td(v.get('hard_safety_counters',{})),td(v.get('settlement',{}).get('settlement_status','pending')),td(v.get('archive',{}).get('capability_archive_entry_id','pending')),td(v.get('archive',{}).get('vnext_reuse_status','pending')),td('available')])+'</tr>' for v in w)
    mrows=''.join('<tr>'+''.join([td(a.get('allocation_id')),td(a.get('vault_id')),td(a.get('assigned_sovereign')),td(a.get('risk_tier')),td(a.get('review_priority')),td(','.join(a.get('validators_required',[]))),td(a.get('allocated_budget_proxy','not_reported')),td(a.get('human_review_required')),td(a.get('auto_merge_allowed'))])+'</tr>' for a in m)
    srows=''.join('<tr>'+''.join([td(x.get('sovereign_name',x.get('sovereign_id'))),td(x.get('domain')),td(x.get('task_family')),td(','.join(x.get('validators',[]))),td(','.join(x.get('allowed_work',[]))),td(','.join(x.get('forbidden_work',[]))),td('pending'),td(sum(1 for v in w if v.get('mark_allocation',{}).get('assigned_sovereign')==x.get('sovereign_id')))])+'</tr>' for x in s)
    body=f"<h1>SecureRails Work Vaults</h1><p>Proof, safety, review, and $AGIALPHA utility settlement containers for AI-agent security governance and proof-bound defensive remediation.</p><h2>Canonical chain</h2><p>{chain}</p><h2>Status cards</h2><pre>{html.escape(json.dumps(sm,indent=2))}</pre><h2>Work Vault table</h2><table border='1'><tr><th>Vault ID</th><th>Status</th><th>Assigned Sovereign</th><th>MARK risk tier</th><th>Review priority</th><th>ProofBundle</th><th>Evidence Docket</th><th>Human review</th><th>Safety</th><th>Settlement</th><th>Capability archived</th><th>vNext reuse</th><th>Raw JSON</th></tr>{wrows}</table><h2>MARK allocation table</h2><table border='1'><tr><th>Allocation ID</th><th>Vault ID</th><th>Assigned Sovereign</th><th>Risk tier</th><th>Review priority</th><th>Validators required</th><th>Utility budget proxy</th><th>Human review required</th><th>Auto-merge allowed</th></tr>{mrows}</table><h2>Sovereign table</h2><table border='1'><tr><th>Sovereign</th><th>Domain</th><th>Task family</th><th>Validators</th><th>Allowed work</th><th>Forbidden work</th><th>Archive entries</th><th>Active vaults</th></tr>{srows}</table><h2>Safety panel</h2><p>raw_secret_leak_count / external_target_scan_count / exploit_execution_count / malware_generation_count / social_engineering_content_count / unsafe_automerge_count / critical_safety_incidents</p><h2>$AGIALPHA utility panel</h2><p>utility budget, validator fee status, replay fee status, α-Work Units, settlement receipt, unused budget status, slashing status for defined misconduct.</p><h2>Workflow buttons</h2><p><a href='https://github.com/MontrealAI/agialpha-first-real-loop/actions/workflows/secure-rails-compliance-guard.yml'>SecureRails Compliance Guard</a> | <a href='https://github.com/MontrealAI/agialpha-first-real-loop/actions/workflows/evidence-hub-publish.yml'>Evidence Mission Control Publisher</a> | <a href='https://github.com/MontrealAI/agialpha-first-real-loop/actions/workflows/replay.yml'>Replay workflow</a> | <a href='https://github.com/MontrealAI/agialpha-first-real-loop/actions/workflows/cyber-ga-sovereign-001-lifecycle.yml'>Cyber-GA Sovereign workflow</a></p><h2>Claim boundary</h2><p>{html.escape(CLAIM)}</p><h2>Human review required</h2><p>true</p><h2>No auto-merge posture</h2><p>auto_merge_allowed: false</p>"
    out.mkdir(parents=True, exist_ok=True)
    (out/'index.html').write_text('<!doctype html><meta charset="utf-8">'+body, encoding='utf-8')
